steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stocksguru-chartmgr:$COMMIT_SHA"
      - "services/chartmgr"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stocksguru-chartmgr:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "stocksguru-chartmgr"
      - "--image"
      - "gcr.io/$PROJECT_ID/stocksguru-chartmgr:$COMMIT_SHA"
      - "--region"
      - "northamerica-northeast2"
      - "--platform"
      - "managed"
      - "--set-env-vars"
      - "DOWNLOADER_BASE_URL=https://stocksguru-downloader-649359984993.northamerica-northeast2.run.app/,ANALYZER_BASE_URL=https://stocksguru-analyzer-649359984993.northamerica-northeast2.run.app/" 
      - "--allow-unauthenticated"
      - "--quiet"

images:
  - "gcr.io/$PROJECT_ID/stocksguru-chartmgr:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY